const englishDatabase = [
  // Batch 1
  { id: 1, word: "the", translation: "o, a, os, as", batch: 1, phonetic: "/the/" },
  { id: 2, word: "be", translation: "ser, estar", batch: 1, phonetic: "/be/" },
  { id: 3, word: "to", translation: "para", batch: 1, phonetic: "/to/" },
  { id: 4, word: "of", translation: "de", batch: 1, phonetic: "/of/" },
  { id: 5, word: "and", translation: "e", batch: 1, phonetic: "/and/" },
  { id: 6, word: "a", translation: "um, uma", batch: 1, phonetic: "/a/" },
  { id: 7, word: "in", translation: "em, dentro", batch: 1, phonetic: "/in/" },
  { id: 8, word: "that", translation: "que, aquele", batch: 1, phonetic: "/that/" },
  { id: 9, word: "have", translation: "ter", batch: 1, phonetic: "/have/" },
  { id: 10, word: "I", translation: "eu", batch: 1, phonetic: "/I/" },
  { id: 11, word: "it", translation: "ele, ela (coisas)", batch: 1, phonetic: "/it/" },
  { id: 12, word: "for", translation: "para, por", batch: 1, phonetic: "/for/" },
  { id: 13, word: "not", translation: "não", batch: 1, phonetic: "/not/" },
  { id: 14, word: "on", translation: "em, sobre", batch: 1, phonetic: "/on/" },
  { id: 15, word: "with", translation: "com", batch: 1, phonetic: "/with/" },
  { id: 16, word: "he", translation: "ele", batch: 1, phonetic: "/he/" },
  { id: 17, word: "as", translation: "como", batch: 1, phonetic: "/as/" },
  { id: 18, word: "you", translation: "você", batch: 1, phonetic: "/you/" },
  { id: 19, word: "do", translation: "fazer", batch: 1, phonetic: "/do/" },
  { id: 20, word: "at", translation: "em (lugar, tempo)", batch: 1, phonetic: "/at/" },
  { id: 21, word: "this", translation: "este, esta", batch: 1, phonetic: "/this/" },
  { id: 22, word: "but", translation: "mas", batch: 1, phonetic: "/but/" },
  { id: 23, word: "his", translation: "dele", batch: 1, phonetic: "/his/" },
  { id: 24, word: "by", translation: "por, ao lado", batch: 1, phonetic: "/by/" },
  { id: 25, word: "from", translation: "de (origem)", batch: 1, phonetic: "/from/" },
  { id: 26, word: "they", translation: "eles, elas", batch: 1, phonetic: "/they/" },
  { id: 27, word: "we", translation: "nós", batch: 1, phonetic: "/we/" },
  { id: 28, word: "say", translation: "dizer", batch: 1, phonetic: "/say/" },
  { id: 29, word: "her", translation: "dela", batch: 1, phonetic: "/her/" },
  { id: 30, word: "she", translation: "ela", batch: 1, phonetic: "/she/" },
  { id: 31, word: "or", translation: "ou", batch: 1, phonetic: "/or/" },
  { id: 32, word: "an", translation: "um, uma", batch: 1, phonetic: "/an/" },
  { id: 33, word: "will", translation: "vai (futuro)", batch: 1, phonetic: "/will/" },
  { id: 34, word: "my", translation: "meu, minha", batch: 1, phonetic: "/my/" },
  { id: 35, word: "one", translation: "um", batch: 1, phonetic: "/one/" },
  { id: 36, word: "all", translation: "todo, todos", batch: 1, phonetic: "/all/" },
  { id: 37, word: "would", translation: "iria", batch: 1, phonetic: "/would/" },
  { id: 38, word: "there", translation: "lá", batch: 1, phonetic: "/there/" },
  { id: 39, word: "their", translation: "deles, delas", batch: 1, phonetic: "/their/" },
  { id: 40, word: "what", translation: "o que", batch: 1, phonetic: "/what/" },
  { id: 41, word: "so", translation: "então, tão", batch: 1, phonetic: "/so/" },
  { id: 42, word: "up", translation: "para cima", batch: 1, phonetic: "/up/" },
  { id: 43, word: "out", translation: "fora", batch: 1, phonetic: "/out/" },
  { id: 44, word: "if", translation: "se", batch: 1, phonetic: "/if/" },
  { id: 45, word: "about", translation: "sobre", batch: 1, phonetic: "/about/" },
  { id: 46, word: "who", translation: "quem", batch: 1, phonetic: "/who/" },
  { id: 47, word: "get", translation: "obter, pegar", batch: 1, phonetic: "/get/" },
  { id: 48, word: "which", translation: "qual, o qual", batch: 1, phonetic: "/which/" },
  { id: 49, word: "go", translation: "ir", batch: 1, phonetic: "/go/" },
  { id: 50, word: "me", translation: "mim, me", batch: 1, phonetic: "/me/" },

  // Batch 2
  { id: 51, word: "when", translation: "quando", batch: 2, phonetic: "/when/" },
  { id: 52, word: "make", translation: "fazer, criar", batch: 2, phonetic: "/make/" },
  { id: 53, word: "can", translation: "poder", batch: 2, phonetic: "/can/" },
  { id: 54, word: "like", translation: "gostar, como", batch: 2, phonetic: "/like/" },
  { id: 55, word: "time", translation: "tempo", batch: 2, phonetic: "/time/" },
  { id: 56, word: "no", translation: "não, nenhum", batch: 2, phonetic: "/no/" },
  { id: 57, word: "just", translation: "apenas, justo", batch: 2, phonetic: "/just/" },
  { id: 58, word: "him", translation: "ele (objeto)", batch: 2, phonetic: "/him/" },
  { id: 59, word: "know", translation: "saber, conhecer", batch: 2, phonetic: "/know/" },
  { id: 60, word: "take", translation: "tomar, levar", batch: 2, phonetic: "/take/" },
  { id: 61, word: "people", translation: "pessoas", batch: 2, phonetic: "/people/" },
  { id: 62, word: "into", translation: "para dentro", batch: 2, phonetic: "/into/" },
  { id: 63, word: "year", translation: "ano", batch: 2, phonetic: "/year/" },
  { id: 64, word: "your", translation: "seu, sua", batch: 2, phonetic: "/your/" },
  { id: 65, word: "good", translation: "bom", batch: 2, phonetic: "/good/" },
  { id: 66, word: "some", translation: "alguns, um pouco", batch: 2, phonetic: "/some/" },
  { id: 67, word: "could", translation: "poderia", batch: 2, phonetic: "/could/" },
  { id: 68, word: "them", translation: "eles, elas (objeto)", batch: 2, phonetic: "/them/" },
  { id: 69, word: "see", translation: "ver", batch: 2, phonetic: "/see/" },
  { id: 70, word: "other", translation: "outro", batch: 2, phonetic: "/other/" },
  { id: 71, word: "than", translation: "do que", batch: 2, phonetic: "/than/" },
  { id: 72, word: "then", translation: "então, depois", batch: 2, phonetic: "/then/" },
  { id: 73, word: "now", translation: "agora", batch: 2, phonetic: "/now/" },
  { id: 74, word: "look", translation: "olhar", batch: 2, phonetic: "/look/" },
  { id: 75, word: "only", translation: "apenas", batch: 2, phonetic: "/only/" },
  { id: 76, word: "come", translation: "vir", batch: 2, phonetic: "/come/" },
  { id: 77, word: "its", translation: "seu, dele (coisas)", batch: 2, phonetic: "/its/" },
  { id: 78, word: "over", translation: "acima, sobre", batch: 2, phonetic: "/over/" },
  { id: 79, word: "think", translation: "pensar", batch: 2, phonetic: "/think/" },
  { id: 80, word: "also", translation: "também", batch: 2, phonetic: "/also/" },
  { id: 81, word: "back", translation: "costas, voltar", batch: 2, phonetic: "/back/" },
  { id: 82, word: "after", translation: "depois", batch: 2, phonetic: "/after/" },
  { id: 83, word: "use", translation: "usar", batch: 2, phonetic: "/use/" },
  { id: 84, word: "two", translation: "dois", batch: 2, phonetic: "/two/" },
  { id: 85, word: "how", translation: "como", batch: 2, phonetic: "/how/" },
  { id: 86, word: "our", translation: "nosso", batch: 2, phonetic: "/our/" },
  { id: 87, word: "work", translation: "trabalhar, trabalho", batch: 2, phonetic: "/work/" },
  { id: 88, word: "first", translation: "primeiro", batch: 2, phonetic: "/first/" },
  { id: 89, word: "well", translation: "bem", batch: 2, phonetic: "/well/" },
  { id: 90, word: "way", translation: "caminho, jeito", batch: 2, phonetic: "/way/" },
  { id: 91, word: "even", translation: "mesmo", batch: 2, phonetic: "/even/" },
  { id: 92, word: "new", translation: "novo", batch: 2, phonetic: "/new/" },
  { id: 93, word: "want", translation: "querer", batch: 2, phonetic: "/want/" },
  { id: 94, word: "because", translation: "porque", batch: 2, phonetic: "/because/" },
  { id: 95, word: "any", translation: "qualquer", batch: 2, phonetic: "/any/" },
  { id: 96, word: "these", translation: "estes", batch: 2, phonetic: "/these/" },
  { id: 97, word: "give", translation: "dar", batch: 2, phonetic: "/give/" },
  { id: 98, word: "day", translation: "dia", batch: 2, phonetic: "/day/" },
  { id: 99, word: "most", translation: "maioria, o mais", batch: 2, phonetic: "/most/" },
  { id: 100, word: "us", translation: "nós (objeto)", batch: 2, phonetic: "/us/" },

  // Batch 3
  { id: 101, word: "is", translation: "é, está", batch: 3, phonetic: "/is/" },
  { id: 102, word: "are", translation: "são, estão", batch: 3, phonetic: "/are/" },
  { id: 103, word: "was", translation: "era, estava", batch: 3, phonetic: "/was/" },
  { id: 104, word: "were", translation: "eram, estavam", batch: 3, phonetic: "/were/" },
  { id: 105, word: "been", translation: "sido, estado", batch: 3, phonetic: "/been/" },
  { id: 106, word: "has", translation: "tem", batch: 3, phonetic: "/has/" },
  { id: 107, word: "had", translation: "tinha", batch: 3, phonetic: "/had/" },
  { id: 108, word: "did", translation: "fez", batch: 3, phonetic: "/did/" },
  { id: 109, word: "does", translation: "faz", batch: 3, phonetic: "/does/" },
  { id: 110, word: "very", translation: "muito", batch: 3, phonetic: "/very/" },
  { id: 111, word: "find", translation: "encontrar", batch: 3, phonetic: "/find/" },
  { id: 112, word: "tell", translation: "contar, dizer", batch: 3, phonetic: "/tell/" },
  { id: 113, word: "ask", translation: "perguntar", batch: 3, phonetic: "/ask/" },
  { id: 114, word: "seem", translation: "parecer", batch: 3, phonetic: "/seem/" },
  { id: 115, word: "feel", translation: "sentir", batch: 3, phonetic: "/feel/" },
  { id: 116, word: "try", translation: "tentar", batch: 3, phonetic: "/try/" },
  { id: 117, word: "leave", translation: "deixar, partir", batch: 3, phonetic: "/leave/" },
  { id: 118, word: "call", translation: "chamar, ligar", batch: 3, phonetic: "/call/" },
  { id: 119, word: "keep", translation: "manter", batch: 3, phonetic: "/keep/" },
  { id: 120, word: "let", translation: "deixar, permitir", batch: 3, phonetic: "/let/" },
  { id: 121, word: "begin", translation: "começar", batch: 3, phonetic: "/begin/" },
  { id: 122, word: "help", translation: "ajudar, ajuda", batch: 3, phonetic: "/help/" },
  { id: 123, word: "show", translation: "mostrar", batch: 3, phonetic: "/show/" },
  { id: 124, word: "hear", translation: "ouvir", batch: 3, phonetic: "/hear/" },
  { id: 125, word: "play", translation: "jogar, tocar", batch: 3, phonetic: "/play/" },
  { id: 126, word: "run", translation: "correr", batch: 3, phonetic: "/run/" },
  { id: 127, word: "move", translation: "mover", batch: 3, phonetic: "/move/" },
  { id: 128, word: "live", translation: "viver, morar", batch: 3, phonetic: "/live/" },
  { id: 129, word: "believe", translation: "acreditar", batch: 3, phonetic: "/believe/" },
  { id: 130, word: "bring", translation: "trazer", batch: 3, phonetic: "/bring/" },
  { id: 131, word: "happen", translation: "acontecer", batch: 3, phonetic: "/happen/" },
  { id: 132, word: "write", translation: "escrever", batch: 3, phonetic: "/write/" },
  { id: 133, word: "provide", translation: "fornecer", batch: 3, phonetic: "/provide/" },
  { id: 134, word: "sit", translation: "sentar", batch: 3, phonetic: "/sit/" },
  { id: 135, word: "stand", translation: "ficar de pé", batch: 3, phonetic: "/stand/" },
  { id: 136, word: "lose", translation: "perder", batch: 3, phonetic: "/lose/" },
  { id: 137, word: "pay", translation: "pagar", batch: 3, phonetic: "/pay/" },
  { id: 138, word: "meet", translation: "encontrar, conhecer", batch: 3, phonetic: "/meet/" },
  { id: 139, word: "include", translation: "incluir", batch: 3, phonetic: "/include/" },
  { id: 140, word: "continue", translation: "continuar", batch: 3, phonetic: "/continue/" },
  { id: 141, word: "set", translation: "configurar, conjunto", batch: 3, phonetic: "/set/" },
  { id: 142, word: "learn", translation: "aprender", batch: 3, phonetic: "/learn/" },
  { id: 143, word: "change", translation: "mudar, mudança", batch: 3, phonetic: "/change/" },
  { id: 144, word: "lead", translation: "liderar", batch: 3, phonetic: "/lead/" },
  { id: 145, word: "understand", translation: "entender", batch: 3, phonetic: "/understand/" },
  { id: 146, word: "watch", translation: "assistir, relógio", batch: 3, phonetic: "/watch/" },
  { id: 147, word: "follow", translation: "seguir", batch: 3, phonetic: "/follow/" },
  { id: 148, word: "stop", translation: "parar", batch: 3, phonetic: "/stop/" },
  { id: 149, word: "create", translation: "criar", batch: 3, phonetic: "/create/" },
  { id: 150, word: "speak", translation: "falar", batch: 3, phonetic: "/speak/" },

  // Batch 4
  { id: 151, word: "read", translation: "ler", batch: 4, phonetic: "/read/" },
  { id: 152, word: "allow", translation: "permitir", batch: 4, phonetic: "/allow/" },
  { id: 153, word: "add", translation: "adicionar", batch: 4, phonetic: "/add/" },
  { id: 154, word: "spend", translation: "gastar, passar (tempo)", batch: 4, phonetic: "/spend/" },
  { id: 155, word: "grow", translation: "crescer", batch: 4, phonetic: "/grow/" },
  { id: 156, word: "open", translation: "abrir", batch: 4, phonetic: "/open/" },
  { id: 157, word: "walk", translation: "caminhar", batch: 4, phonetic: "/walk/" },
  { id: 158, word: "win", translation: "vencer", batch: 4, phonetic: "/win/" },
  { id: 159, word: "offer", translation: "oferecer", batch: 4, phonetic: "/offer/" },
  { id: 160, word: "remember", translation: "lembrar", batch: 4, phonetic: "/remember/" },
  { id: 161, word: "love", translation: "amar, amor", batch: 4, phonetic: "/love/" },
  { id: 162, word: "consider", translation: "considerar", batch: 4, phonetic: "/consider/" },
  { id: 163, word: "appear", translation: "aparecer", batch: 4, phonetic: "/appear/" },
  { id: 164, word: "buy", translation: "comprar", batch: 4, phonetic: "/buy/" },
  { id: 165, word: "wait", translation: "esperar", batch: 4, phonetic: "/wait/" },
  { id: 166, word: "serve", translation: "servir", batch: 4, phonetic: "/serve/" },
  { id: 167, word: "die", translation: "morrer", batch: 4, phonetic: "/die/" },
  { id: 168, word: "send", translation: "enviar", batch: 4, phonetic: "/send/" },
  { id: 169, word: "expect", translation: "esperar (expectativa)", batch: 4, phonetic: "/expect/" },
  { id: 170, word: "build", translation: "construir", batch: 4, phonetic: "/build/" },
  { id: 171, word: "stay", translation: "ficar", batch: 4, phonetic: "/stay/" },
  { id: 172, word: "fall", translation: "cair, outono", batch: 4, phonetic: "/fall/" },
  { id: 173, word: "cut", translation: "cortar", batch: 4, phonetic: "/cut/" },
  { id: 174, word: "reach", translation: "alcançar", batch: 4, phonetic: "/reach/" },
  { id: 175, word: "kill", translation: "matar", batch: 4, phonetic: "/kill/" },
  { id: 176, word: "remain", translation: "permanecer", batch: 4, phonetic: "/remain/" },
  { id: 177, word: "suggest", translation: "sugerir", batch: 4, phonetic: "/suggest/" },
  { id: 178, word: "raise", translation: "levantar, criar", batch: 4, phonetic: "/raise/" },
  { id: 179, word: "pass", translation: "passar", batch: 4, phonetic: "/pass/" },
  { id: 180, word: "sell", translation: "vender", batch: 4, phonetic: "/sell/" },
  { id: 181, word: "require", translation: "exigir", batch: 4, phonetic: "/require/" },
  { id: 182, word: "report", translation: "relatar, relatório", batch: 4, phonetic: "/report/" },
  { id: 183, word: "decide", translation: "decidir", batch: 4, phonetic: "/decide/" },
  { id: 184, word: "pull", translation: "puxar", batch: 4, phonetic: "/pull/" },
  { id: 185, word: "break", translation: "quebrar", batch: 4, phonetic: "/break/" },
  { id: 186, word: "support", translation: "apoiar, suporte", batch: 4, phonetic: "/support/" },
  { id: 187, word: "return", translation: "retornar", batch: 4, phonetic: "/return/" },
  { id: 188, word: "explain", translation: "explicar", batch: 4, phonetic: "/explain/" },
  { id: 189, word: "hope", translation: "esperar (esperança)", batch: 4, phonetic: "/hope/" },
  { id: 190, word: "develop", translation: "desenvolver", batch: 4, phonetic: "/develop/" },
  { id: 191, word: "carry", translation: "carregar", batch: 4, phonetic: "/carry/" },
  { id: 192, word: "thank", translation: "agradecer", batch: 4, phonetic: "/thank/" },
  { id: 193, word: "receive", translation: "receber", batch: 4, phonetic: "/receive/" },
  { id: 194, word: "join", translation: "juntar-se", batch: 4, phonetic: "/join/" },
  { id: 195, word: "agree", translation: "concordar", batch: 4, phonetic: "/agree/" },
  { id: 196, word: "pick", translation: "escolher, pegar", batch: 4, phonetic: "/pick/" },
  { id: 197, word: "wear", translation: "vestir, usar", batch: 4, phonetic: "/wear/" },
  { id: 198, word: "base", translation: "base, basear", batch: 4, phonetic: "/base/" },
  { id: 199, word: "produce", translation: "produzir", batch: 4, phonetic: "/produce/" },
  { id: 200, word: "face", translation: "rosto, enfrentar", batch: 4, phonetic: "/face/" },

  // Batch 5
  { id: 201, word: "cover", translation: "cobrir, capa", batch: 5, phonetic: "/cover/" },
  { id: 202, word: "catch", translation: "pegar, capturar", batch: 5, phonetic: "/catch/" },
  { id: 203, word: "draw", translation: "desenhar", batch: 5, phonetic: "/draw/" },
  { id: 204, word: "choose", translation: "escolher", batch: 5, phonetic: "/choose/" },
  { id: 205, word: "cause", translation: "causa, causar", batch: 5, phonetic: "/cause/" },
  { id: 206, word: "point", translation: "ponto, apontar", batch: 5, phonetic: "/point/" },
  { id: 207, word: "listen", translation: "escutar", batch: 5, phonetic: "/listen/" },
  { id: 208, word: "realize", translation: "perceber", batch: 5, phonetic: "/realize/" },
  { id: 209, word: "place", translation: "lugar, colocar", batch: 5, phonetic: "/place/" },
  { id: 210, word: "close", translation: "fechar, perto", batch: 5, phonetic: "/close/" },
  { id: 211, word: "involve", translation: "envolver", batch: 5, phonetic: "/involve/" },
  { id: 212, word: "increase", translation: "aumentar", batch: 5, phonetic: "/increase/" },
  { id: 213, word: "seek", translation: "buscar", batch: 5, phonetic: "/seek/" },
  { id: 214, word: "act", translation: "agir, ato", batch: 5, phonetic: "/act/" },
  { id: 215, word: "fight", translation: "lutar", batch: 5, phonetic: "/fight/" },
  { id: 216, word: "throw", translation: "lançar", batch: 5, phonetic: "/throw/" },
  { id: 217, word: "fill", translation: "preencher", batch: 5, phonetic: "/fill/" },
  { id: 218, word: "drop", translation: "deixar cair, gota", batch: 5, phonetic: "/drop/" },
  { id: 219, word: "plan", translation: "planejar, plano", batch: 5, phonetic: "/plan/" },
  { id: 220, word: "push", translation: "empurrar", batch: 5, phonetic: "/push/" },
  { id: 221, word: "reduce", translation: "reduzir", batch: 5, phonetic: "/reduce/" },
  { id: 222, word: "note", translation: "nota, notar", batch: 5, phonetic: "/note/" },
  { id: 223, word: "enter", translation: "entrar", batch: 5, phonetic: "/enter/" },
  { id: 224, word: "share", translation: "compartilhar", batch: 5, phonetic: "/share/" },
  { id: 225, word: "save", translation: "salvar, economizar", batch: 5, phonetic: "/save/" },
  { id: 226, word: "protect", translation: "proteger", batch: 5, phonetic: "/protect/" },
  { id: 227, word: "occur", translation: "ocorrer", batch: 5, phonetic: "/occur/" },
  { id: 228, word: "accept", translation: "aceitar", batch: 5, phonetic: "/accept/" },
  { id: 229, word: "identify", translation: "identificar", batch: 5, phonetic: "/identify/" },
  { id: 230, word: "determine", translation: "determinar", batch: 5, phonetic: "/determine/" },
  { id: 231, word: "prepare", translation: "preparar", batch: 5, phonetic: "/prepare/" },
  { id: 232, word: "argue", translation: "discutir, argumentar", batch: 5, phonetic: "/argue/" },
  { id: 233, word: "recognize", translation: "reconhecer", batch: 5, phonetic: "/recognize/" },
  { id: 234, word: "indicate", translation: "indicar", batch: 5, phonetic: "/indicate/" },
  { id: 235, word: "wonder", translation: "maravilhar-se, imaginar", batch: 5, phonetic: "/wonder/" },
  { id: 236, word: "lay", translation: "deitar, colocar", batch: 5, phonetic: "/lay/" },
  { id: 237, word: "fail", translation: "falhar", batch: 5, phonetic: "/fail/" },
  { id: 238, word: "arrive", translation: "chegar", batch: 5, phonetic: "/arrive/" },
  { id: 239, word: "design", translation: "projetar, design", batch: 5, phonetic: "/design/" },
  { id: 240, word: "name", translation: "nome, nomear", batch: 5, phonetic: "/name/" },
  { id: 241, word: "present", translation: "presente, apresentar", batch: 5, phonetic: "/present/" },
  { id: 242, word: "compare", translation: "comparar", batch: 5, phonetic: "/compare/" },
  { id: 243, word: "represent", translation: "representar", batch: 5, phonetic: "/represent/" },
  { id: 244, word: "shoot", translation: "atirar", batch: 5, phonetic: "/shoot/" },
  { id: 245, word: "prove", translation: "provar", batch: 5, phonetic: "/prove/" },
  { id: 246, word: "hang", translation: "pendurar", batch: 5, phonetic: "/hang/" },
  { id: 247, word: "forget", translation: "esquecer", batch: 5, phonetic: "/forget/" },
  { id: 248, word: "claim", translation: "reivindicar", batch: 5, phonetic: "/claim/" },
  { id: 249, word: "remove", translation: "remover", batch: 5, phonetic: "/remove/" },
  { id: 250, word: "sound", translation: "som, soar", batch: 5, phonetic: "/sound/" },

  // Batch 6
  { id: 251, word: "enjoy", translation: "aproveitar", batch: 6, phonetic: "/enjoy/" },
  { id: 252, word: "form", translation: "formar, forma", batch: 6, phonetic: "/form/" },
  { id: 253, word: "establish", translation: "estabelecer", batch: 6, phonetic: "/establish/" },
  { id: 254, word: "visit", translation: "visitar", batch: 6, phonetic: "/visit/" },
  { id: 255, word: "care", translation: "cuidar, cuidado", batch: 6, phonetic: "/care/" },
  { id: 256, word: "avoid", translation: "evitar", batch: 6, phonetic: "/avoid/" },
  { id: 257, word: "imagine", translation: "imaginar", batch: 6, phonetic: "/imagine/" },
  { id: 258, word: "head", translation: "cabeça, liderar", batch: 6, phonetic: "/head/" },
  { id: 259, word: "control", translation: "controlar, controle", batch: 6, phonetic: "/control/" },
  { id: 260, word: "apply", translation: "aplicar", batch: 6, phonetic: "/apply/" },
  { id: 261, word: "reveal", translation: "revelar", batch: 6, phonetic: "/reveal/" },
  { id: 262, word: "finish", translation: "terminar", batch: 6, phonetic: "/finish/" },
  { id: 263, word: "store", translation: "loja, armazenar", batch: 6, phonetic: "/store/" },
  { id: 264, word: "maintain", translation: "manter", batch: 6, phonetic: "/maintain/" },
  { id: 265, word: "designate", translation: "designar", batch: 6, phonetic: "/designate/" },
  { id: 266, word: "contain", translation: "conter", batch: 6, phonetic: "/contain/" },
  { id: 267, word: "measure", translation: "medir, medida", batch: 6, phonetic: "/measure/" },
  { id: 268, word: "discuss", translation: "discutir", batch: 6, phonetic: "/discuss/" },
  { id: 269, word: "address", translation: "endereço, abordar", batch: 6, phonetic: "/address/" },
  { id: 270, word: "test", translation: "teste, testar", batch: 6, phonetic: "/test/" },
  { id: 271, word: "improve", translation: "melhorar", batch: 6, phonetic: "/improve/" },
  { id: 272, word: "discover", translation: "descobrir", batch: 6, phonetic: "/discover/" },
  { id: 273, word: "manage", translation: "gerenciar", batch: 6, phonetic: "/manage/" },
  { id: 274, word: "exist", translation: "existir", batch: 6, phonetic: "/exist/" },
  { id: 275, word: "recognise", translation: "reconhecer", batch: 6, phonetic: "/recognise/" },
  { id: 276, word: "treat", translation: "tratar", batch: 6, phonetic: "/treat/" },
  { id: 277, word: "reflect", translation: "refletir", batch: 6, phonetic: "/reflect/" },
  { id: 278, word: "assume", translation: "assumir", batch: 6, phonetic: "/assume/" },
  { id: 279, word: "guess", translation: "adivinhar", batch: 6, phonetic: "/guess/" },
  { id: 280, word: "sing", translation: "cantar", batch: 6, phonetic: "/sing/" },
  { id: 281, word: "record", translation: "gravar, registro", batch: 6, phonetic: "/record/" },
  { id: 282, word: "vote", translation: "votar", batch: 6, phonetic: "/vote/" },
  { id: 283, word: "check", translation: "checar", batch: 6, phonetic: "/check/" },
  { id: 284, word: "laugh", translation: "rir", batch: 6, phonetic: "/laugh/" },
  { id: 285, word: "notice", translation: "notar, aviso", batch: 6, phonetic: "/notice/" },
  { id: 286, word: "perform", translation: "realizar, atuar", batch: 6, phonetic: "/perform/" },
  { id: 287, word: "mention", translation: "mencionar", batch: 6, phonetic: "/mention/" },
  { id: 288, word: "relate", translation: "relacionar", batch: 6, phonetic: "/relate/" },
  { id: 289, word: "affect", translation: "afetar", batch: 6, phonetic: "/affect/" },
  { id: 290, word: "travel", translation: "viajar", batch: 6, phonetic: "/travel/" },
  { id: 291, word: "defend", translation: "defender", batch: 6, phonetic: "/defend/" },
  { id: 292, word: "express", translation: "expressar", batch: 6, phonetic: "/express/" },
  { id: 293, word: "argue", translation: "discutir", batch: 6, phonetic: "/argue/" },
  { id: 294, word: "focus", translation: "focar, foco", batch: 6, phonetic: "/focus/" },
  { id: 295, word: "prevent", translation: "prevenir", batch: 6, phonetic: "/prevent/" },
  { id: 296, word: "suffer", translation: "sofrer", batch: 6, phonetic: "/suffer/" },
  { id: 297, word: "demand", translation: "exigir, demanda", batch: 6, phonetic: "/demand/" },
  { id: 298, word: "commit", translation: "cometer, comprometer", batch: 6, phonetic: "/commit/" },
  { id: 299, word: "influence", translation: "influenciar", batch: 6, phonetic: "/influence/" },
  { id: 300, word: "hurt", translation: "machucar", batch: 6, phonetic: "/hurt/" },

  // Batch 7
  { id: 301, word: "prepare", translation: "preparar", batch: 7, phonetic: "/prepare/" },
  { id: 302, word: "solve", translation: "resolver", batch: 7, phonetic: "/solve/" },
  { id: 303, word: "attend", translation: "comparecer", batch: 7, phonetic: "/attend/" },
  { id: 304, word: "relate", translation: "relatar", batch: 7, phonetic: "/relate/" },
  { id: 305, word: "encourage", translation: "encorajar", batch: 7, phonetic: "/encourage/" },
  { id: 306, word: "connect", translation: "conectar", batch: 7, phonetic: "/connect/" },
  { id: 307, word: "belong", translation: "pertencer", batch: 7, phonetic: "/belong/" },
  { id: 308, word: "advise", translation: "aconselhar", batch: 7, phonetic: "/advise/" },
  { id: 309, word: "destroy", translation: "destruir", batch: 7, phonetic: "/destroy/" },
  { id: 310, word: "divide", translation: "dividir", batch: 7, phonetic: "/divide/" },
  { id: 311, word: "explore", translation: "explorar", batch: 7, phonetic: "/explore/" },
  { id: 312, word: "organize", translation: "organizar", batch: 7, phonetic: "/organize/" },
  { id: 313, word: "predict", translation: "prever", batch: 7, phonetic: "/predict/" },
  { id: 314, word: "replace", translation: "substituir", batch: 7, phonetic: "/replace/" },
  { id: 315, word: "survive", translation: "sobreviver", batch: 7, phonetic: "/survive/" },
  { id: 316, word: "adapt", translation: "adaptar", batch: 7, phonetic: "/adapt/" },
  { id: 317, word: "calculate", translation: "calcular", batch: 7, phonetic: "/calculate/" },
  { id: 318, word: "compete", translation: "competir", batch: 7, phonetic: "/compete/" },
  { id: 319, word: "distribute", translation: "distribuir", batch: 7, phonetic: "/distribute/" },
  { id: 320, word: "estimate", translation: "estimar", batch: 7, phonetic: "/estimate/" },
  { id: 321, word: "guarantee", translation: "garantir", batch: 7, phonetic: "/guarantee/" },
  { id: 322, word: "investigate", translation: "investigar", batch: 7, phonetic: "/investigate/" },
  { id: 323, word: "negotiate", translation: "negociar", batch: 7, phonetic: "/negotiate/" },
  { id: 324, word: "overcome", translation: "superar", batch: 7, phonetic: "/overcome/" },
  { id: 325, word: "preserve", translation: "preservar", batch: 7, phonetic: "/preserve/" },
  { id: 326, word: "resolve", translation: "resolver", batch: 7, phonetic: "/resolve/" },
  { id: 327, word: "suspect", translation: "suspeitar", batch: 7, phonetic: "/suspect/" },
  { id: 328, word: "translate", translation: "traduzir", batch: 7, phonetic: "/translate/" },
  { id: 329, word: "update", translation: "atualizar", batch: 7, phonetic: "/update/" },
  { id: 330, word: "yield", translation: "render, ceder", batch: 7, phonetic: "/yield/" },
  { id: 331, word: "analyze", translation: "analisar", batch: 7, phonetic: "/analyze/" },
  { id: 332, word: "communicate", translation: "comunicar", batch: 7, phonetic: "/communicate/" },
  { id: 333, word: "demonstrate", translation: "demonstrar", batch: 7, phonetic: "/demonstrate/" },
  { id: 334, word: "evaluate", translation: "avaliar", batch: 7, phonetic: "/evaluate/" },
  { id: 335, word: "identify", translation: "identificar", batch: 7, phonetic: "/identify/" },
  { id: 336, word: "justify", translation: "justificar", batch: 7, phonetic: "/justify/" },
  { id: 337, word: "operate", translation: "operar", batch: 7, phonetic: "/operate/" },
  { id: 338, word: "participate", translation: "participar", batch: 7, phonetic: "/participate/" },
  { id: 339, word: "qualify", translation: "qualificar", batch: 7, phonetic: "/qualify/" },
  { id: 340, word: "react", translation: "reagir", batch: 7, phonetic: "/react/" },
  { id: 341, word: "satisfy", translation: "satisfazer", batch: 7, phonetic: "/satisfy/" },
  { id: 342, word: "transform", translation: "transformar", batch: 7, phonetic: "/transform/" },
  { id: 343, word: "verify", translation: "verificar", batch: 7, phonetic: "/verify/" },
  { id: 344, word: "witness", translation: "testemunhar", batch: 7, phonetic: "/witness/" },
  { id: 345, word: "absorb", translation: "absorver", batch: 7, phonetic: "/absorb/" },
  { id: 346, word: "breathe", translation: "respirar", batch: 7, phonetic: "/breathe/" },
  { id: 347, word: "calculate", translation: "calcular", batch: 7, phonetic: "/calculate/" },
  { id: 348, word: "dare", translation: "ousar", batch: 7, phonetic: "/dare/" },
  { id: 349, word: "educate", translation: "educar", batch: 7, phonetic: "/educate/" },
  { id: 350, word: "float", translation: "flutuar", batch: 7, phonetic: "/float/" },

  // Batch 8
  { id: 351, word: "generate", translation: "gerar", batch: 8, phonetic: "/generate/" },
  { id: 352, word: "hesitate", translation: "hesitar", batch: 8, phonetic: "/hesitate/" },
  { id: 353, word: "illustrate", translation: "ilustrar", batch: 8, phonetic: "/illustrate/" },
  { id: 354, word: "jump", translation: "pular", batch: 8, phonetic: "/jump/" },
  { id: 355, word: "kiss", translation: "beijar", batch: 8, phonetic: "/kiss/" },
  { id: 356, word: "launch", translation: "lançar", batch: 8, phonetic: "/launch/" },
  { id: 357, word: "manage", translation: "gerenciar", batch: 8, phonetic: "/manage/" },
  { id: 358, word: "nominate", translation: "nominar", batch: 8, phonetic: "/nominate/" },
  { id: 359, word: "observe", translation: "observar", batch: 8, phonetic: "/observe/" },
  { id: 360, word: "pause", translation: "pausar", batch: 8, phonetic: "/pause/" },
  { id: 361, word: "quote", translation: "citar", batch: 8, phonetic: "/quote/" },
  { id: 362, word: "recover", translation: "recuperar", batch: 8, phonetic: "/recover/" },
  { id: 363, word: "select", translation: "selecionar", batch: 8, phonetic: "/select/" },
  { id: 364, word: "tackle", translation: "enfrentar, lidar", batch: 8, phonetic: "/tackle/" },
  { id: 365, word: "unite", translation: "unir", batch: 8, phonetic: "/unite/" },
  { id: 366, word: "value", translation: "valorizar", batch: 8, phonetic: "/value/" },
  { id: 367, word: "weigh", translation: "pesar", batch: 8, phonetic: "/weigh/" },
  { id: 368, word: "yell", translation: "gritar", batch: 8, phonetic: "/yell/" },
  { id: 369, word: "accuse", translation: "acusar", batch: 8, phonetic: "/accuse/" },
  { id: 370, word: "blame", translation: "culpar", batch: 8, phonetic: "/blame/" },
  { id: 371, word: "celebrate", translation: "celebrar", batch: 8, phonetic: "/celebrate/" },
  { id: 372, word: "debate", translation: "debater", batch: 8, phonetic: "/debate/" },
  { id: 373, word: "embrace", translation: "abraçar", batch: 8, phonetic: "/embrace/" },
  { id: 374, word: "forgive", translation: "perdoar", batch: 8, phonetic: "/forgive/" },
  { id: 375, word: "gather", translation: "reunir", batch: 8, phonetic: "/gather/" },
  { id: 376, word: "handle", translation: "lidar, manusear", batch: 8, phonetic: "/handle/" },
  { id: 377, word: "imply", translation: "implicar", batch: 8, phonetic: "/imply/" },
  { id: 378, word: "judge", translation: "julgar", batch: 8, phonetic: "/judge/" },
  { id: 379, word: "knock", translation: "bater", batch: 8, phonetic: "/knock/" },
  { id: 380, word: "lock", translation: "trancar", batch: 8, phonetic: "/lock/" },
  { id: 381, word: "match", translation: "combinar", batch: 8, phonetic: "/match/" },
  { id: 382, word: "navigate", translation: "navegar", batch: 8, phonetic: "/navigate/" },
  { id: 383, word: "obtain", translation: "obter", batch: 8, phonetic: "/obtain/" },
  { id: 384, word: "pack", translation: "empacotar", batch: 8, phonetic: "/pack/" },
  { id: 385, word: "quit", translation: "desistir, sair", batch: 8, phonetic: "/quit/" },
  { id: 386, word: "rely", translation: "depender, confiar", batch: 8, phonetic: "/rely/" },
  { id: 387, word: "shift", translation: "mudar, deslocar", batch: 8, phonetic: "/shift/" },
  { id: 388, word: "teach", translation: "ensinar", batch: 8, phonetic: "/teach/" },
  { id: 389, word: "urge", translation: "estimular, urgir", batch: 8, phonetic: "/urge/" },
  { id: 390, word: "vary", translation: "variar", batch: 8, phonetic: "/vary/" },
  { id: 391, word: "warn", translation: "avisar", batch: 8, phonetic: "/warn/" },
  { id: 392, word: "acknowledge", translation: "reconhecer", batch: 8, phonetic: "/acknowledge/" },
  { id: 393, word: "borrow", translation: "pegar emprestado", batch: 8, phonetic: "/borrow/" },
  { id: 394, word: "capture", translation: "capturar", batch: 8, phonetic: "/capture/" },
  { id: 395, word: "defend", translation: "defender", batch: 8, phonetic: "/defend/" },
  { id: 396, word: "emerge", translation: "emergir", batch: 8, phonetic: "/emerge/" },
  { id: 397, word: "feature", translation: "apresentar, destacar", batch: 8, phonetic: "/feature/" },
  { id: 398, word: "guide", translation: "guiar", batch: 8, phonetic: "/guide/" },
  { id: 399, word: "hunt", translation: "caçar", batch: 8, phonetic: "/hunt/" },
  { id: 400, word: "incorporate", translation: "incorporar", batch: 8, phonetic: "/incorporate/" },

  // Batch 9
  { id: 401, word: "abandon", translation: "abandonar", batch: 9, phonetic: "/abandon/" },
  { id: 402, word: "abuse", translation: "abusar", batch: 9, phonetic: "/abuse/" },
  { id: 403, word: "accommodate", translation: "acomodar", batch: 9, phonetic: "/accommodate/" },
  { id: 404, word: "achieve", translation: "alcançar", batch: 9, phonetic: "/achieve/" },
  { id: 405, word: "acquire", translation: "adquirir", batch: 9, phonetic: "/acquire/" },
  { id: 406, word: "adjust", translation: "ajustar", batch: 9, phonetic: "/adjust/" },
  { id: 407, word: "administer", translation: "administrar", batch: 9, phonetic: "/administer/" },
  { id: 408, word: "admit", translation: "admitir", batch: 9, phonetic: "/admit/" },
  { id: 409, word: "adopt", translation: "adotar", batch: 9, phonetic: "/adopt/" },
  { id: 410, word: "advance", translation: "avançar", batch: 9, phonetic: "/advance/" },
  { id: 411, word: "advise", translation: "aconselhar", batch: 9, phonetic: "/advise/" },
  { id: 412, word: "afford", translation: "poder pagar, arcar", batch: 9, phonetic: "/afford/" },
  { id: 413, word: "aim", translation: "mirar, objetivar", batch: 9, phonetic: "/aim/" },
  { id: 414, word: "alter", translation: "alterar", batch: 9, phonetic: "/alter/" },
  { id: 415, word: "amount", translation: "totalizar, somar", batch: 9, phonetic: "/amount/" },
  { id: 416, word: "anticipate", translation: "antecipar", batch: 9, phonetic: "/anticipate/" },
  { id: 417, word: "apologize", translation: "pedir desculpas", batch: 9, phonetic: "/apologize/" },
  { id: 418, word: "appeal", translation: "apelar", batch: 9, phonetic: "/appeal/" },
  { id: 419, word: "apply", translation: "aplicar", batch: 9, phonetic: "/apply/" },
  { id: 420, word: "appoint", translation: "nomear", batch: 9, phonetic: "/appoint/" },
  { id: 421, word: "appreciate", translation: "apreciar", batch: 9, phonetic: "/appreciate/" },
  { id: 422, word: "approach", translation: "aproximar", batch: 9, phonetic: "/approach/" },
  { id: 423, word: "approve", translation: "aprovar", batch: 9, phonetic: "/approve/" },
  { id: 424, word: "arise", translation: "surgir", batch: 9, phonetic: "/arise/" },
  { id: 425, word: "arrange", translation: "arranjar", batch: 9, phonetic: "/arrange/" },
  { id: 426, word: "arrive", translation: "chegar", batch: 9, phonetic: "/arrive/" },
  { id: 427, word: "assess", translation: "avaliar", batch: 9, phonetic: "/assess/" },
  { id: 428, word: "assign", translation: "atribuir", batch: 9, phonetic: "/assign/" },
  { id: 429, word: "assist", translation: "assistir, ajudar", batch: 9, phonetic: "/assist/" },
  { id: 430, word: "associate", translation: "associar", batch: 9, phonetic: "/associate/" },
  { id: 431, word: "assume", translation: "assumir", batch: 9, phonetic: "/assume/" },
  { id: 432, word: "assure", translation: "assegurar", batch: 9, phonetic: "/assure/" },
  { id: 433, word: "attach", translation: "anexar", batch: 9, phonetic: "/attach/" },
  { id: 434, word: "attack", translation: "atacar", batch: 9, phonetic: "/attack/" },
  { id: 435, word: "attain", translation: "atingir", batch: 9, phonetic: "/attain/" },
  { id: 436, word: "attempt", translation: "tentar", batch: 9, phonetic: "/attempt/" },
  { id: 437, word: "attend", translation: "comparecer", batch: 9, phonetic: "/attend/" },
  { id: 438, word: "attract", translation: "atrair", batch: 9, phonetic: "/attract/" },
  { id: 439, word: "avoid", translation: "evitar", batch: 9, phonetic: "/avoid/" },
  { id: 440, word: "award", translation: "premiar", batch: 9, phonetic: "/award/" },
  { id: 441, word: "bake", translation: "assar", batch: 9, phonetic: "/bake/" },
  { id: 442, word: "balance", translation: "equilibrar", batch: 9, phonetic: "/balance/" },
  { id: 443, word: "ban", translation: "banir", batch: 9, phonetic: "/ban/" },
  { id: 444, word: "bare", translation: "desnudar, descobrir", batch: 9, phonetic: "/bare/" },
  { id: 445, word: "bathe", translation: "banhar", batch: 9, phonetic: "/bathe/" },
  { id: 446, word: "bear", translation: "suportar, urso", batch: 9, phonetic: "/bear/" },
  { id: 447, word: "beat", translation: "bater, vencer", batch: 9, phonetic: "/beat/" },
  { id: 448, word: "become", translation: "tornar-se", batch: 9, phonetic: "/become/" },
  { id: 449, word: "beg", translation: "implorar", batch: 9, phonetic: "/beg/" },
  { id: 450, word: "behave", translation: "comportar-se", batch: 9, phonetic: "/behave/" },

  // Batch 10
  { id: 451, word: "bend", translation: "dobrar", batch: 10, phonetic: "/bend/" },
  { id: 452, word: "benefit", translation: "beneficiar", batch: 10, phonetic: "/benefit/" },
  { id: 453, word: "bet", translation: "apostar", batch: 10, phonetic: "/bet/" },
  { id: 454, word: "bind", translation: "atar", batch: 10, phonetic: "/bind/" },
  { id: 455, word: "bite", translation: "morder", batch: 10, phonetic: "/bite/" },
  { id: 456, word: "blame", translation: "culpar", batch: 10, phonetic: "/blame/" },
  { id: 457, word: "bleed", translation: "sangrar", batch: 10, phonetic: "/bleed/" },
  { id: 458, word: "blend", translation: "misturar", batch: 10, phonetic: "/blend/" },
  { id: 459, word: "bless", translation: "abençoar", batch: 10, phonetic: "/bless/" },
  { id: 460, word: "blind", translation: "cegar", batch: 10, phonetic: "/blind/" },
  { id: 461, word: "blink", translation: "piscar", batch: 10, phonetic: "/blink/" },
  { id: 462, word: "block", translation: "bloquear", batch: 10, phonetic: "/block/" },
  { id: 463, word: "blow", translation: "soprar", batch: 10, phonetic: "/blow/" },
  { id: 464, word: "boast", translation: "gabar-se", batch: 10, phonetic: "/boast/" },
  { id: 465, word: "boil", translation: "ferver", batch: 10, phonetic: "/boil/" },
  { id: 466, word: "book", translation: "reservar", batch: 10, phonetic: "/book/" },
  { id: 467, word: "border", translation: "fazer fronteira", batch: 10, phonetic: "/border/" },
  { id: 468, word: "borrow", translation: "pegar emprestado", batch: 10, phonetic: "/borrow/" },
  { id: 469, word: "bother", translation: "incomodar", batch: 10, phonetic: "/bother/" },
  { id: 470, word: "bounce", translation: "quicar", batch: 10, phonetic: "/bounce/" },
  { id: 471, word: "bow", translation: "curvar-se", batch: 10, phonetic: "/bow/" },
  { id: 472, word: "brand", translation: "marcar", batch: 10, phonetic: "/brand/" },
  { id: 473, word: "bridge", translation: "ligar, fazer ponte", batch: 10, phonetic: "/bridge/" },
  { id: 474, word: "broaden", translation: "ampliar", batch: 10, phonetic: "/broaden/" },
  { id: 475, word: "brush", translation: "escovar", batch: 10, phonetic: "/brush/" },
  { id: 476, word: "budget", translation: "orçar", batch: 10, phonetic: "/budget/" },
  { id: 477, word: "bump", translation: "bater, colidir", batch: 10, phonetic: "/bump/" },
  { id: 478, word: "burn", translation: "queimar", batch: 10, phonetic: "/burn/" },
  { id: 479, word: "burst", translation: "estourar", batch: 10, phonetic: "/burst/" },
  { id: 480, word: "bury", translation: "enterrar", batch: 10, phonetic: "/bury/" },
  { id: 481, word: "calculate", translation: "calcular", batch: 10, phonetic: "/calculate/" },
  { id: 482, word: "cancel", translation: "cancelar", batch: 10, phonetic: "/cancel/" },
  { id: 483, word: "care", translation: "cuidar", batch: 10, phonetic: "/care/" },
  { id: 484, word: "carry", translation: "carregar", batch: 10, phonetic: "/carry/" },
  { id: 485, word: "carve", translation: "esculpir", batch: 10, phonetic: "/carve/" },
  { id: 486, word: "cast", translation: "lançar", batch: 10, phonetic: "/cast/" },
  { id: 487, word: "catch", translation: "pegar", batch: 10, phonetic: "/catch/" },
  { id: 488, word: "cause", translation: "causar", batch: 10, phonetic: "/cause/" },
  { id: 489, word: "cease", translation: "cessar", batch: 10, phonetic: "/cease/" },
  { id: 490, word: "celebrate", translation: "celebrar", batch: 10, phonetic: "/celebrate/" },
  { id: 491, word: "challenge", translation: "desafiar", batch: 10, phonetic: "/challenge/" },
  { id: 492, word: "change", translation: "mudar", batch: 10, phonetic: "/change/" },
  { id: 493, word: "charge", translation: "cobrar, carregar", batch: 10, phonetic: "/charge/" },
  { id: 494, word: "chase", translation: "perseguir", batch: 10, phonetic: "/chase/" },
  { id: 495, word: "chat", translation: "bater papo", batch: 10, phonetic: "/chat/" },
  { id: 496, word: "check", translation: "checar", batch: 10, phonetic: "/check/" },
  { id: 497, word: "cheer", translation: "torcer, animar", batch: 10, phonetic: "/cheer/" },
  { id: 498, word: "chew", translation: "mastigar", batch: 10, phonetic: "/chew/" },
  { id: 499, word: "choose", translation: "escolher", batch: 10, phonetic: "/choose/" },
  { id: 500, word: "chop", translation: "picar", batch: 10, phonetic: "/chop/" }
];

const phonemesDatabase = [
  { id: 1001, symbol: "/iː/", word: "see", translation: "Som longo (see)", phonetic: "/iː/", audio: "phoneme_i_long", approximations: ["ee", "e", "i", "ea", "he", "she", "see", "sea"] },
  { id: 1002, symbol: "/uː/", word: "too", translation: "Som longo (too)", phonetic: "/uː/", audio: "phoneme_u_long", approximations: ["oo", "u", "ou", "o", "two", "too", "you", "who"] },
  { id: 1003, symbol: "/ɑː/", word: "father", translation: "Som longo (father)", phonetic: "/ɑː/", audio: "phoneme_a_long", approximations: ["a", "ah", "ar", "far", "father"] },
  { id: 1004, symbol: "/ɪ/", word: "sit", translation: "Som curto (sit)", phonetic: "/ɪ/", audio: "phoneme_i_short", approximations: ["i", "e", "it", "sit", "is"] },
  { id: 1005, symbol: "/ʊ/", word: "book", translation: "Som curto (book)", phonetic: "/ʊ/", audio: "phoneme_u_short", approximations: ["u", "oo", "ou", "book", "look", "good"] },
  { id: 1006, symbol: "/æ/", word: "cat", translation: "Som curto (cat)", phonetic: "/æ/", audio: "phoneme_a_short", approximations: ["a", "e", "cat", "bat", "at", "an"] },
  { id: 1007, symbol: "/θ/", word: "think", translation: "Consoante complexa (think)", phonetic: "/θ/", audio: "phoneme_th_unvoiced", approximations: ["th", "t", "f", "think", "thanks", "with"] },
  { id: 1008, symbol: "/ð/", word: "this", translation: "Consoante complexa (this)", phonetic: "/ð/", audio: "phoneme_th_voiced", approximations: ["th", "d", "v", "the", "this", "that"] },
  { id: 1009, symbol: "/ʃ/", word: "she", translation: "Consoante complexa (she)", phonetic: "/ʃ/", audio: "phoneme_sh", approximations: ["sh", "ch", "s", "she", "show", "shoe"] },
  { id: 1010, symbol: "/tʃ/", word: "cheese", translation: "Consoante complexa (cheese)", phonetic: "/tʃ/", audio: "phoneme_ch", approximations: ["ch", "sh", "t", "cheese", "chair", "catch"] }
];
